apiVersion: v1
kind: Service
metadata:
  name: delivery-api-rest
  labels:
    app: delivery-api-rest
spec:
  ports:
    - port: 8080
  selector:
    app: delivery-api-rest
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api-rest
  labels:
    app: delivery-api-rest
spec:
  selector:
    matchLabels:
      app: delivery-api-rest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: delivery-api-rest
    spec:
      containers:
        - image: matheusinit/delivery-service-spring:latest
          name: delivery-api-rest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-api-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-api-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-api-secrets
                  key: POSTGRES_URL
            - name: KAFKA_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-api-secrets
                  key: KAFKA_URL
          ports:
            - containerPort: 8080
      restartPolicy: Always
