apiVersion: v1
kind: Service
metadata:
  name: ecommerce-kafka-queue
  labels:
    app: ecommerce-kafka-queue
spec:
  ports:
    - port: 9092
  selector:
    app: ecommerce-kafka-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-kafka-queue
  labels:
    app: ecommerce-kafka-queue
spec:
  selector:
    matchLabels:
      app: ecommerce-kafka-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ecommerce-kafka-queue
    spec:
      containers:
        - image: bitnami/kafka:latest
          name: ecommerce-kafka-queue
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@0.0.0.0:9093
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
          ports:
            - containerPort: 9092
